### ISSUE TITLE
`dm` package not listed in dependencies

### ISSUE THREAD

**Issue by newville** [BCDA-APS/apsbss#41]
With current master branch (2.0.0, @1be308), I get 

```
~> apsbss -l
(base) cars4:apsbss>apsbss -l
Traceback (most recent call last):
  File "/home/xas_user/xraylarch/bin/apsbss", line 5, in <module>
    from apsbss.apsbss import main
  File "/home/xas_user/Codes/apsbss/apsbss/apsbss.py", line 51, in <module>
    from .server_interface import Server
  File "/home/xas_user/Codes/apsbss/apsbss/server_interface.py", line 17, in <module>
    import dm
ModuleNotFoundError: No module named 'dm'
```

I don't see an appropriate `dm` package.  Is that `aps-dm-api`?

**Comment by prjemian** [comment]
Yes. Only conda install. It pins python to <3.12

**Comment by newville** [comment]
@prjemian Ah, great, thanks -- I will try that.

**Comment by newville** [comment]
Thanks, that worked!

FWIW, using 

   (py311) >export DM_APS_DB_WEB_SERVICE_URL='https:///catdtn01.aps.anl.gov:11236' 
   (py311) >apsbss beamlines


works for me to list beamlines, and I can also get a list of proposals and ESAFS.  Great!!

**Comment by prjemian** [comment]
Thanks for testing!  That's on Sinisa and his team!

**Comment by prjemian** [comment]
Try the search.  Here's an example for you:

```bash
$ apsbss search 13-BM-C school -r recent
Search: beamline='13-BM-C' runs='recent' query='school'
====== ============================== ====== ======================================== ====
id     pi                             run    title                                    type
====== ============================== ====== ======================================== ====
258639 Yongseong Choi <ychoi@anl.gov> 2022-2 National School on Neutron and X-ray ... ESAF
259117 Carlo Segre <segre@iit.edu>    2022-2 2022 IIT/APS EXAFS Summer School         ESAF
====== ============================== ====== ======================================== ====
```

**Comment by prjemian** [comment]
@newville Feel free to close this issue.
